Fix mythic.py for use with existing API tokens
When you use this Mythic API wrapper with an existing API token instead
of a username and password, this duplicate call `self._apitoken =
apitoken` overwrites `self._apitoken` with the string value of your
token--clobbering the instance of `APIToken` that was just set on the
line before it.

Later on when that value is used, the SDK will complain that the string
doesn't have a `token_value` attribute:

    AttributeError: 'str' object has no attribute 'token_value'